sudo: false

language: python

python:
  - "2.7"

env:
  - NUMPY_VERSION="1.10" PANDAS_VERSION="0.17"
  - NUMPY_VERSION="1.11" PANDAS_VERSION="0.18"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

  # Install dependencies
  - conda env create --name bfd --file environment.yml
  - source activate bfd
  - conda install --yes numpy=$NUMPY_VERSION pandas=$PANDAS_VERSION

script:
  - pip install -e .
  - flake8
  - PYTHONPATH=.:PYTHONPATH py.test -v

notifications:
  email: false
